### ISSUE TITLE
Unable to find correct/free version of qt?

### ISSUE THREAD

**Issue by Hokage3211** [OpenMAR/PiTool#1]
I went to the qt link, but after downloading the installer under the "open-source" zone, the legacy versions only go back to 5.9.0, and not 5.8.0
![image](https://user-images.githubusercontent.com/54164358/65546456-6b83b880-decc-11e9-8969-6ba598706897.png)

so what and how are we supposed to install qt, and I hope for free? If you could provide a better link and instructions, I would very much appreciate input.

**Comment by lonetech** [comment]
https://code.qt.io/cgit/qt/qt5.git/ appears to have older versions. The flashy installer the main website links to doesn't seem to go back much. That said, I wouldn't be surprised if 5.9 was close enough.

**Comment by Hokage3211** [comment]
Thank you for the link, but I'm not quite sure how to install that then. I've got this https://codereview.qt-project.org/c/qt/qt5/+/182765 but the git commands don't seem to work, at least maybe I'm making a mistake? I haven't used git for a little so please forgive me on that.

**Comment by Hokage3211** [comment]
Okay wait, I've gotten a download now, and have the files, what do I do with this now, then? I'm not quite sure what QT is, I assumed it was an editor to work on the codebase, but I'm not sure what .exe to run from the downloaded files?

**Comment by Hokage3211** [comment]
Alright, so I think I've figured out this is a visual studio project, and while I can't load the project on my visual studio, the answer given is correct for the issue, so I'll just mark that as correct and see if I can figure out what's up with my visual studio.

**Comment by Hokage3211** [comment]
Redirecting this issue to a summary post, to be more efficient possibly. 
https://github.com/OpenMAR/PiTool/issues/3
